codetoanalyze/cpp/pulse-17/make_unique.cpp, make_unique_ptr::make_unique0_bad, 5, NULLPTR_DEREFERENCE, no_bucket, ERROR, [is assigned to the constant 42,assigned,in call to `std::make_unique<int,_int>`,parameter `__args` of std::make_unique<int,_int>,in call to `std::forward<int>`,parameter `__t` of std::forward<int>,returned,return from call to `std::forward<int>`,assigned,return from call to `std::make_unique<int,_int>`,taking "then" branch,is assigned to the null pointer,assigned,invalid access occurs here]
codetoanalyze/cpp/pulse-17/make_unique.cpp, make_unique_ptr::make_unique1_bad, 5, USE_AFTER_DELETE, no_bucket, ERROR, [invalidation part of the trace starts here,in call to `make_unique_ptr::X::X`,allocated by call to `new` (modelled),assigned,return from call to `make_unique_ptr::X::X`,when calling `make_unique_ptr::X::~X` here,parameter `this` of make_unique_ptr::X::~X,when calling `make_unique_ptr::X::__infer_inner_destructor_~X` here,parameter `this` of make_unique_ptr::X::__infer_inner_destructor_~X,was invalidated by `delete`,use-after-lifetime part of the trace starts here,in call to `make_unique_ptr::X::X`,allocated by call to `new` (modelled),assigned,return from call to `make_unique_ptr::X::X`,in call to `std::make_unique<make_unique_ptr::X,_make_unique_ptr::X>`,parameter `__args` of std::make_unique<make_unique_ptr::X,_make_unique_ptr::X>,in call to `std::forward<make_unique_ptr::X>`,parameter `__t` of std::forward<make_unique_ptr::X>,returned,return from call to `std::forward<make_unique_ptr::X>`,in call to `make_unique_ptr::X::X`,parameter `__param_0` of make_unique_ptr::X::X,assigned,return from call to `make_unique_ptr::X::X`,return from call to `std::make_unique<make_unique_ptr::X,_make_unique_ptr::X>`,when calling `make_unique_ptr::X::~X` here,parameter `this` of make_unique_ptr::X::~X,when calling `make_unique_ptr::X::__infer_inner_destructor_~X` here,parameter `this` of make_unique_ptr::X::__infer_inner_destructor_~X,invalid access occurs here]
codetoanalyze/cpp/pulse-17/make_unique.cpp, make_unique_ptr::make_unique2_bad, 6, USE_AFTER_DELETE, no_bucket, ERROR, [invalidation part of the trace starts here,in call to `make_unique_ptr::X::X`,allocated by call to `new` (modelled),assigned,return from call to `make_unique_ptr::X::X`,in call to `std::make_unique<56462c074508ed>`,parameter `__args` of std::make_unique<56462c074508ed>,in call to `std::forward<make_unique_ptr::X_&>`,parameter `__t` of std::forward<make_unique_ptr::X_&>,returned,return from call to `std::forward<make_unique_ptr::X_&>`,in call to `make_unique_ptr::X::X`,parameter `__param_0` of make_unique_ptr::X::X,assigned,return from call to `make_unique_ptr::X::X`,return from call to `std::make_unique<56462c074508ed>`,when calling `make_unique_ptr::X::~X` here,parameter `this` of make_unique_ptr::X::~X,when calling `make_unique_ptr::X::__infer_inner_destructor_~X` here,parameter `this` of make_unique_ptr::X::__infer_inner_destructor_~X,was invalidated by `delete`,use-after-lifetime part of the trace starts here,in call to `make_unique_ptr::X::X`,allocated by call to `new` (modelled),assigned,return from call to `make_unique_ptr::X::X`,when calling `make_unique_ptr::X::~X` here,parameter `this` of make_unique_ptr::X::~X,when calling `make_unique_ptr::X::__infer_inner_destructor_~X` here,parameter `this` of make_unique_ptr::X::__infer_inner_destructor_~X,invalid access occurs here]
codetoanalyze/cpp/pulse-17/make_unique.cpp, make_unique_ptr::make_unique_ptr_release_bad, 2, MEMORY_LEAK_CPP, no_bucket, ERROR, [allocation part of the trace starts here,when calling `std::make_unique<make_unique_ptr::X>` here,when calling `make_unique_ptr::X::X` here,allocated by `new` here,memory becomes unreachable here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, std_not_none_check_value_ok_FP, 5, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `std::optional::optional(Value arg)` (modelled),assigned,taking "then" branch,in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, std_none_no_check_bad, 2, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, std_none_copy_bad, 3, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,in call to `std::optional::optional(std::optional<Value> arg)` (modelled),invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, std_assign_bad, 5, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,in call to `std::optional::operator=(std::optional<Value> arg)` (modelled),invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, std_assign2_bad, 4, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `std::optional::operator=(None)` (modelled),is assigned an empty value,invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, FP_std_value_or_check_value_ok, 5, NULLPTR_DEREFERENCE, no_bucket, ERROR, [in call to `std::optional::optional(Value arg)` (modelled),in call to `std::optional::value_or() non-empty case` (modelled),assigned,taking "then" branch,in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,invalid access occurs here]
codetoanalyze/cpp/pulse-17/std_optional.cpp, might_return_none, 0, PULSE_CONST_REFABLE, no_bucket, ERROR, [Parameter x]
codetoanalyze/cpp/pulse-17/std_optional.cpp, inside_try_catch_FP, 3, OPTIONAL_EMPTY_ACCESS, no_bucket, ERROR, [in call to `might_return_none`,parameter `b` of might_return_none,taking "then" branch,in call to `std::optional::optional(=nullopt)` (modelled),is assigned an empty value,return from call to `might_return_none`,invalid access occurs here]
